### ISSUE TITLE
All data table is not showing all data

### ISSUE THREAD

**Issue by jmason-ebi** [mpi2/PhenotypeData#234]
The gene page has a tab labelled "all data" that should show all data we have for the gene.

![image](https://user-images.githubusercontent.com/1931551/72425409-ac575400-377f-11ea-8b9d-44be1568c24b.png)

This table is currently missing some of the data.  We've done some preliminary digging and think this is due to the source the data is coming from.  If the table is reading all results from the stats-result core, it would exclude data that is not analyzed. 

Ensure that the list of rows in the all data table are coming from the experimental data API.

ACCEPTANCE CRITERIA:
1) All data that comes from queries to the experiment core for a gene should appear on the all data table for that gene.
2) Ensure that the Gene page for Cib2 include a link in the all data tab to the PP3_S parameter: https://www.mousephenotype.org/data/charts?accession=MGI:1929293&allele_accession_id=MGI:5548707&zygosity=homozygote&parameter_stable_id=IMPC_ACS_009_001&pipeline_stable_id=HRWL_001

Example:
Gene: Cib2 https://www.mousephenotype.org/data/genes/MGI:1929293
Experiment core results: https://www.ebi.ac.uk/mi/impc/solr/experiment/select?q=gene_accession_id:%22MGI:1929293%22&rows=2147483647

**Comment by jwgwarren** [comment]
This needs some major work as we don't have a call to experiment and only have gp core currently?? Then we need to mesh the results....

**Comment by jwgwarren** [comment]
ok - found this code todo that is what needs to be done in the ExperimentsController which is new to me:

//TODO: Change to request all the data from the expirement core and overlay the s-r core results onto this
        // set

**Comment by jwgwarren** [comment]
ok - found this code todo that is what needs to be done in the ExperimentsController which is new to me but is still work which is why it hasn't been done!!? as still relies on SR core at the moment which obviously we can't do:

//TODO: Change to request all the data from the expirement core and overlay the s-r core results onto this
        // set

**Comment by jwgwarren** [comment]
issue now is that for different parameters they are not in the SR core for different reasons? Some have assigned p values by centers others like lacz and Xray have no pvalues or analysis?

**Comment by jwgwarren** [comment]
comments from V:

From a user's point of view, "No statistical method" or "No statistical result" is not informative, while displaying "Not applicable" provides an explanation. Can we show "Not applicable"?

Displaying the outcome of the test is more complicated because we rely on the p-value for this, but there is no p-value in these cases (where no statistical test was performed). May be adding an additional column with the MP term associated to the test would solve this issue, as well as being generally useful, also for tests with statistical tests and p-values.

Why is the number of mutants zero in all cases?

**Comment by jwgwarren** [comment]
working on refactoring this. Issue now is as we are showing all data we have a lot of lacZ data that really has little value. e.g. Adult LacZ/ Brain Stem - result "Not Applicable" so need to filter these out. 885 results in table and thats just using male results.

**Comment by jwgwarren** [comment]
set chart links on rows where there is no StatsResult to be display false.

**Comment by jwgwarren** [comment]
Changing image rows to point at something useful or have no link at all.

**Comment by jmason-ebi** [comment]
Also folded in to the fix of the all data table filter by life stage.

**Comment by jmason-ebi** [comment]
Deployed to live

**Comment by viomunoz** [comment]
Comments on this task:
1.- There are still problems with data display. See this:
https://www.mousephenotype.org/data/genes/MGI:1096391?dataLifeStage=embryo

![Screenshot 2020-03-13 at 10.53.33.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/a58028ed-acfa-4850-9104-0c9ff9e1214c)

2.- Do we need the column "Status"? Is not the P-value column enough? If there is a P-value being shown, then we know the experiment was Successful, otherwise we could show here alternative categories "Not enough data" or "Not applicable" (we may prefer to avoid showing P-values of 1.00 when no statistical test was conducted?).
And this is what you see when you click on one of the rows with P-value=1, for example: https://www.mousephenotype.org/data/charts?accession=MGI:1096391&allele_accession_id=MGI:5636923&parameter_stable_id=IMPC_CSD_025_001&zygosity=heterozygote&phenotyping_center=MRC%20Harwell&pipeline_stable_id=HRWL_001

![Screenshot 2020-03-13 at 11.00.41.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/c2c81723-8fcc-4116-9dcc-b4eab1b53df3)

**Comment by viomunoz** [comment]
Will make this into 2 new tickets.
