### ISSUE TITLE
Same colony ID, but different allele

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#261]
**We have noted:**
- there are alleles with phenotype information in the IMPC website but no phenotype colony in iMits;
- the same colony ID is associated to different alleles in iMits.

See attached screenshots for gene Klf14:

https://www.mousephenotype.org/data/genes/MGI:3577024

---

iMits shows:
- two different colonies were phenotyped, with alleles tm1.1 and em1 (Klf14<tm1.1(KOMP)Vlcg> , Klf14<em1(IMPC)H>)
- colony ID BL1129 has allele tm1 but also allele tm1.1

IMPC website shows:
- phenotyped data for alleles tm1.1 and em1, but also tm1 (Klf14<tm1.1(KOMP)Vlcg> , Klf14<em1(IMPC)H>, Klf14<tm1(KOMP)Vlcg>)

---

**Need to find out:**
1. Where does the tm1 information come from?
2. How many colonies IDs are associated to more than one allele?

---
**Screenshots:**

iMits for gene Klf14:

![Screenshot 2020-01-24 at 12.28.31.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/99490927-caef-4b4b-b330-b1c43b5e38d8)

---

IMPC website, gene page for gene Klf14, All data table:

![Screenshot 2020-01-24 at 12.29.33.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/3d56b309-9e7b-4102-8559-51380bfd83ba)

**Comment by jmason-ebi** [comment]
We've found the issue.  This issue has been fixed by the center since the last time we did a data release.  Please see: https://www.i-dcc.org/imits/phenotype_attempts/39/history

Entry 5.  This record used to be named colony BL1129 (gene Klf14), this was then updated to colony name ET10082.  There is already a BL1129 in the system associated with gene Klf14, and the new colony is associated to gene Ccdc92.

This is not a software issue.
DR 11.0 will resolve this issue on the portal.
Closing as resolved
