### ISSUE TITLE
Items in top level menu "Publications" > "Data supporting IMPC papers": order not stable

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#367]
**Issue:**
When you visit the pages under Publications > Data supporting IMPC papers, the items in the menu change order.

When you come to the site:

![Screenshot 2020-05-15 at 21.19.33.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/600563f5-9aee-4abe-ad55-d86432b0ea63)

------------------
After clicking to see the metabolism page, the items in that menu get rearranged:

![Screenshot 2020-05-15 at 21.17.12.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/362c2b97-403d-4ea6-a288-79ded52608ed)

------------------

**Requirement:** 
Order to be stable
Perhaps this order (the one the items have on when you enter the site)

![Screenshot 2020-05-15 at 21.15.46.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/5224daa6-4ef9-4687-b4bd-5dcee2ffae3c)

**Comment by amccoy95** [comment]
The issue here is that as this is showing the data pages for the latest papers, WordPress is sorting these in order of published date, but the applications outside of WordPress are sorting alphabetically as they don't have this information. 

I can see about adding the published date to the menu json
