### ISSUE TITLE
Add publications section to the gene page

### ISSUE THREAD

**Issue by jmason-ebi** [mpi2/PhenotypeData#400]
Per the last DAWG call, there has been a request that we add associated publications to a gene page.  Can these be retrieved from the publication service on a gene-by-gene basis?

**Comment by viomunoz** [comment]
There might be **two options** in which we could link IMPC-related publications to the Gene Page:
1.- Have a **link at the top left-hand corner of the Gene Page** that redirects to the [Publication page](https://www.mousephenotype.org/data/publications) filtered by gene.
Disadvantages: 
- is this link easy to miss? (However, it has a prominent position in the Gene page);
- redirection to a page that may show one publication (but user may be able ot realize is filterd by gene).
Advantages: 
- connects Gene Page with Publications page (avoding dead ends as recommended from the user expert, users discover a new page they had not come across before, we could even think of making alleles clickable so they send the user to the Gene Page)
- does not interfer with the structure of the Gene page. 

2.- Adding a section "Publications" to the Gene page, it could be after Disease Models and before Order information.
Disadvantages: 
- makes the Gene page longer
- requires adding an icon to the top part of the page that redirects the user to this new section (in order to keep up with the Gene page design)
- this publication section will be variable in length depending on the number of publications retrieved (e.g. "Cib2" returns no publications, "Spns2" returns 6 publications; could be solved by showing always one publication and make it expandable on clicking)
Advantages: 
- visibility is high
- could be developed into a section with additional information about the gene, as expressed in the DAWG meeting.

**Comment by jmason-ebi** [comment]
Decided to go for option 2.  Will add section to the Gee page just before the order section.
 [ ] - Section called Publications (#)
 [ ] - Publications icon fa-book on the bottom row (between Histopath and Order)
 [ ] - Default showing 5 publications per page (most recent first)

**Comment by jwgwarren** [comment]
Should I start working on this in JSP?

**Comment by jwgwarren** [comment]
so it looks like there is some disconnect now between the solr cores which I believe do show some Femur significance scores using the femur significance parameter and the category field - however this does not show in the histopath view on the web page:

http://localhost:8080/PhenotypeArchive_war/histopath/MGI:1335088

query https://wwwdev.ebi.ac.uk/mi/impc/dev/solr/experiment/select?q=parameter_stable_id:IMPC_HIS_229_001&fq=category:1

result:
experiment_id: "b077040df6da064ac147ef8ba55d427b",
specimen_id: "9313a084247e375265cd063596dc02cd",
observation_id: "704b120855b88f6eb3fc38e4f5da7cbc",
allele_accession_id: "MGI:5755044",
gene_accession_id: "MGI:1335088",
project_name: "NorCOMM2",
strain_accession_id: "MGI:2683688",
litter_id: "13540",
phenotyping_center: "TCP",
external_sample_id: "ABYR_96_349196",
developmental_stage_name: "postnatal",
developmental_stage_acc: "EFO:0002948",
datasource_name: "IMPC",
age_in_days: 977,
date_of_birth: "2015-07-12T00:00:00Z",
metadata: [
"Experimenter ID = 101110",
"Section thickness = 4",
"Severity maximum score = 4",
"Stain = H&E"
],
metadata_group: "d41d8cd98f00b204e9800998ecf8427e",
procedure_sequence_id: "1",
experiment_source_id: "Histopathology_1898",
gene_symbol: "Pstpip2",
biological_sample_group: "experimental",
sex: "male",
allele_symbol: "Pstpip2<em1(IMPC)Tcp>",
production_center: "TCP",
age_in_weeks: 139,
colony_id: "TCPR0319_em1",
zygosity: "homozygote",
allelic_composition: "Pstpip2<em1(IMPC)Tcp>/Pstpip2<em1(IMPC)Tcp>",
pipeline_name: "TCP Pipeline",
pipeline_stable_id: "TCP_001",
procedure_name: "Histopathology",
procedure_stable_id: "IMPC_HIS_002",
procedure_group: "IMPC_HIS",
parameter_name: "Femur - Significance score",
parameter_stable_id: "IMPC_HIS_229_001",
observation_type: "categorical",
category: "1",
strain_name: "C57BL/6NCrl",
genetic_background: "involves: C57BL/6NCrl",
date_of_experiment: "2018-03-15T00:00:00Z",
life_stage_name: "Early adult",
life_stage_acc: "IMPCLS:0005",
id: "81264917-3bf4-41bc-b188-8e61ad8e4e49",
_version_: 1676012624788062200

**Comment by jwgwarren** [comment]
I will open another ticket for this bug as it's a different issue than the title of this one.

**Comment by jmason-ebi** [comment]
Started.

**Comment by jmason-ebi** [comment]
Deployed on BETA 

http://beta.mousephenotype.org/data/genes/MGI:1919884

![image.png](https://images.zenhubusercontent.com/5e26d9c19aca8856dc57b8c7/26779ffb-8890-4f3a-9f70-dfd03fe650c2)
