### ISSUE TITLE
Essential genes data portal: duplicated rows?

### ISSUE THREAD

**Issue by viomunoz** [mpi2/PhenotypeData#544]
Validation of the EG prototype before release, ticket #464 
https://wwwdev.ebi.ac.uk/~federico/phenotype-data/essential-genes 

**Issue:**
Some rows seem to be duplicated, but didnt  see any differences between them. Is there any internal data we are not releasing that is causing these lines to appear duplicated?

**List:**
MGI:103075 
MGI:2444401
MGI:1921357

**Output:**
MGI:103075 – one row expected, two rows appear
MGI:2444401 – two rows expected, four rows appear
MGI:1921357 – two rows expected, four rows appear

**Requirement:** 
Only one row when results are identical

**Screenshot:**
(Only partial view of table is possible)

![Screenshot 2021-02-09 at 15.33.03.png](https://images.zenhubusercontent.com/5e271bb2e33c5e6b469a910f/2a15b6b7-8b2a-469c-abca-988f0631cd77)

**Comment by mrelac-ebi** [comment]
For MGI:103075, the duplicate rows are due to differing viability data from the impc_adult_viability table.
Query: 

```
        SELECT mg.*,
          cav.*, iev.*
        FROM mouse_gene mg
        LEFT OUTER JOIN combined_adult_viability cav ON cav.mouse_gene_id = mg.id
        LEFT OUTER JOIN impc_embryo_viability iev ON iev.mouse_gene_id = mg.id
		where mg.mgi_gene_acc_id = 'MGI:103075'
```

Data:
id | parameter_stable_id | procedure_group | procedure_stable_id | life_stage_acc | experiment_source_id | procedure_name
-- | -- | -- | -- | -- | -- | --
2125 | IMPC_EVL_001_001 | IMPC_EVL | IMPC_EVL_001 | IMPCLS:0001 | IMPC_EVL_001-TCPA0163Cre | ViabilityE9.5SecondaryScreen
2126 | IMPC_EVM_001_001 | IMPC_EVM | IMPC_EVM_001 | IMPCLS:0002 | IMPC_EVM_001-TCPA0163Cre | ViabilityE12.5SecondaryScreen

**Comment by mrelac-ebi** [comment]
This spreadsheet shows the source of duplicate rows for both CAV and IAV:
[essentialgenes dup bug 544.xlsx](https://github.com/mpi2/PhenotypeData/files/5972093/essentialgenes.dup.bug.544.xlsx)

**Comment by jmason-ebi** [comment]
After discussion with @viomunoz , yes, please remove the impc_embryo_viability joins from the query and rebuild and push the core.  This should remove the duplication issue where there is no visible reason for the duplication.

**Comment by mrelac-ebi** [comment]
impc_embryo_viability is now removed, and only the minimal set of required fields from combined_adult_viability are used, thus eliminating duplicates.
