### ISSUE TITLE
Change the placing of the Phenotype Grid in the Gene Page to make the relation with the 'All measurements' section more evident

### ISSUE THREAD

**Issue by ficolo** [mpi2/PhenotypeData#71]
People did not expect the grid to be a filtering mechanism for the All measurements data. Some never realised the connection between the two. Making the Phenotype Grid horizontal and putting it closer to the 'All measurements' section could facilitate the connection.

![Slide62](https://user-images.githubusercontent.com/2343039/57386371-1872c880-71ac-11e9-9599-2a498aa59422.png)

**Comment by viomunoz** [comment]
Requirements, after meeting with user expert:

- Separate "All measurements" tab in 2 tabs: one for a subset of the measurements, depiciting the horizontal Manhattan plot / chart view, and indeed an "All measurements" tab for the table. (In addition to lack of accuracy becasue the chart does not depict all measurements, users completely missed the button on the right to change between the chart and table view.)
- Add an explanation as to what the user is seeing in each tab. For example: 

1. Chart tab: "This is a subset of all measurements taken for the KO line for gene XXX. Results shown are those for which a statistical test was performed; in the few cases in which the same parameter was measured in more than one KO line, the most signficant resuts is shown. Change to the "All mesaurements" tab to view all measurements";
2. Table tab: "All measurements taken for the KO line for gene XXX".

- Incorporate filters, on each tab. Add an explanation; for example: "Use filters to select specific results and view them in more detail".
- Became evident that we need to offer filtering by physiological system and procedure; a minimum will be by physiological system.
- Filters on chart tab are most challenging, as they will influence how data are shown in the chart plot. Several possibilities were discussed and are being considered. When we first arrive to the chart tab, all filters are selected, so an overview of the results is presented (as currently; but, currently, a selection of the results is shown). One possibility that was considered: 1. For the presentation/first view, when user opens the tab: procedures on the y-axis (instead of parameters) and dots along the x-axis direction (p-value), in two colours that alteranate for each procedure; 2. When the user starts to select physiological tests and/or procedures manually, the chart changes to procedure view on y-axis.

**Comment by jmason-ebi** [comment]
Where are the other comments from github?  This comment is meant to sync the history between https://app.zenhub.com/workspaces/cda-5e26daa5fe6fac729f87218d/issues/mpi2/phenotypedata/71 and https://github.com/mpi2/PhenotypeData/issues/71

**Comment by jmason-ebi** [comment]
We have made several updates to the functionality and layout of this widget -- enough to require a new round of UI testing if further refinements are required.
